POST http://localhost:7071/api/workflow/trigger HTTP/1.1
Content-Type: application/json

{
  "pg_host_prod": "advpsqlfxuk",
  "pg_host_dev": "advpsqlfxukdev",
  "pg_database": "test01",
  "pg_user": "alfonsod",
  "resource_group": "adv_data_rg"
}

GET http://localhost:7071/api/workflow/status HTTP/1.1


curl -X POST http://localhost:7071/api/workflow/trigger \
  -H "Content-Type: application/json" \
  -d '{
    "pg_host_prod": "advpsqlfxuk",
    "pg_host_dev": "advpsqlfxukdev",
    "pg_database": "test01",
    "pg_user": "alfonsod",
    "resource_group": "adv_data_rg"
  }'