name: PostgreSQL Backup and Restore

on:
  workflow_dispatch:  # For manual activation
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  backup-restore:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install PostgreSQL client tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set environment variables
        run: |
          echo "PG_HOST_PROD=${{ secrets.PG_HOST_PROD }}" >> $GITHUB_ENV
          echo "PG_HOST_DEV=${{ secrets.PG_HOST_DEV }}" >> $GITHUB_ENV
          echo "PG_DATABASE=${{ secrets.PG_DATABASE }}" >> $GITHUB_ENV
          echo "PG_USER=${{ secrets.PG_USER }}" >> $GITHUB_ENV
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_CONTAINER=${{ secrets.AZURE_STORAGE_CONTAINER }}" >> $GITHUB_ENV
          echo "PGPASSWORD=${{ secrets.PG_PASSWORD }}" >> $GITHUB_ENV
      
      - name: Create backup
        run: |
          chmod +x ./scripts/backup.sh
          ./scripts/backup.sh
        
      - name: Restore from backup
        run: |
          chmod +x ./scripts/restore.sh
          ./scripts/restore.sh