name: PostgreSQL Backup and Restore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "DATABASE_NAME=test01" >> $GITHUB_ENV
          echo "SOURCE_SERVER=prodpssql01" >> $GITHUB_ENV
          echo "DEST_SERVER=devpssql01" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT=pssqlstorage" >> $GITHUB_ENV
          echo "BACKUP_FILE=backup.sql"

      - name: Backup PostgreSQL database
        run: |
          chmod +x ./scripts/backup.sh
          ./scripts/backup.sh

  restore:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore PostgreSQL database
        run: |
          chmod +x ./scripts/restore.sh
          ./scripts/restore.sh